# __PROJECT_NAME__

This local ranking season project was generated by zeroServer `scripts/NewLocalGame.java --template ranking-season`.

## Run

First install the current zeroServer SNAPSHOT into the local Maven repository:

~~~powershell
mvn -q -DskipTests install
~~~

Then run these commands in this project directory:

~~~powershell
mvn -q clean test
mvn -q exec:java
~~~

Expected output:

~~~text
ranking-season=ok|mode=local|name=__PROJECT_NAME__|summary=season=season-2,players=1,top=1001:300,player=1001,rank=1,score=300,resets=1,lastAction=rank:1001=1|logs=9|metrics=8|maxProtocolId=95107
~~~

## Layout

~~~text
src/main/protocol/RankingSeason.si
src/main/protocol/protoId.txt
src/main/java/__PACKAGE_PATH__/__APP_CLASS__.java
src/test/java/__PACKAGE_PATH__/__TEST_CLASS__.java
BUSINESS_GUIDE.md
COMPONENTS.md
NEXT_STEPS.md
zero-scaffold.json
~~~

The Maven `generate-sources` phase calls `zero-codegen` and writes generated ranking season protocol sources to:

~~~text
target/generated-sources/zero-codegen
~~~

## Next Business Step

After the first run, open `BUSINESS_GUIDE.md` and follow `First Business Change` before adding broader systems.

## Components

Read `BUSINESS_GUIDE.md` for business editing points, protocol changes and local verification commands.
Read `COMPONENTS.md` for the generated protocol flow, framework touchpoints and production gap.
Read `NEXT_STEPS.md` for promotion checklist and high-risk stop points.
Read `zero-scaffold.json` when a tool needs machine-readable scaffold metadata.

## Boundaries

- This project is a local / prototype ranking season scaffold.
- It serializes season ranking state through a local Actor lane.
- It demonstrates score submit, top query, player-rank query and season reset only.
- It does not implement Redis sorted set, cross-server ranking, settlement, rewards, anti-cheat, idempotent compensation or capacity planning.
- The default selection does not connect external middleware or open network ports. Adding Redis requires an external service at startup.
- It is not a production RankingService / SeasonService API commitment.
