<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>__PACKAGE__</groupId>
    <artifactId>__PROJECT_NAME__</artifactId>
    <version>0.1.0-SNAPSHOT</version>

    <name>__PROJECT_NAME__</name>
    <description>zeroServer local scene sync scaffold.</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>21</maven.compiler.release>
        <zero.version>__ZERO_VERSION__</zero.version>
        <junit.jupiter.version>5.10.3</junit.jupiter.version>
        <exec.mainClass>__PACKAGE__.__APP_CLASS__</exec.mainClass>
    </properties>

    <dependencies>
        <dependency>
            <groupId>group.zn.zero</groupId>
            <artifactId>zero-server-starter</artifactId>
            <version>${zero.version}</version>
        </dependency>
        <dependency>
            <groupId>group.zn.zero</groupId>
            <artifactId>zero-codegen</artifactId>
            <version>${zero.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
                <configuration>
                    <useModulePath>false</useModulePath>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>generate-zero-protocol</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <configuration>
                            <mainClass>group.zn.zero.codegen.ProtocolCodegenCli</mainClass>
                            <classpathScope>compile</classpathScope>
                            <arguments>
                                <argument>--input</argument>
                                <argument>${project.basedir}/src/main/protocol</argument>
                                <argument>--protoId</argument>
                                <argument>${project.basedir}/src/main/protocol/protoId.txt</argument>
                                <argument>--out</argument>
                                <argument>${project.build.directory}/generated-sources/zero-codegen</argument>
                                <argument>--pkg</argument>
                                <argument>__PACKAGE__.generated</argument>
                                <argument>--languages</argument>
                                <argument>java</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>${exec.mainClass}</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>add-zero-protocol-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/zero-codegen</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
