# __PROJECT_NAME__

This local scene sync project was generated by zeroServer `scripts/NewLocalGame.java --template scene-sync`.

## Run

First install the current zeroServer SNAPSHOT into the local Maven repository:

~~~powershell
mvn -q -DskipTests install
~~~

Then run these commands in this project directory:

~~~powershell
mvn -q clean test
mvn -q exec:java
~~~

Expected output:

~~~text
scene-sync=ok|mode=local|name=__PROJECT_NAME__|summary=scene=scene-1,entities=3,focus=1001,visible=2,visibleIds=1002,1003,lastDelta=move:1003@8,8|logs=6|metrics=5|maxProtocolId=92105
~~~

## Layout

~~~text
src/main/protocol/SceneSync.si
src/main/protocol/protoId.txt
src/main/java/__PACKAGE_PATH__/__APP_CLASS__.java
src/test/java/__PACKAGE_PATH__/__TEST_CLASS__.java
BUSINESS_GUIDE.md
COMPONENTS.md
NEXT_STEPS.md
zero-scaffold.json
~~~

The Maven `generate-sources` phase calls `zero-codegen` and writes generated scene-sync protocol sources to:

~~~text
target/generated-sources/zero-codegen
~~~

## Next Business Step

After the first run, open `BUSINESS_GUIDE.md` and follow `First Business Change` before adding broader systems.

## Components

Read `BUSINESS_GUIDE.md` for business editing points, protocol changes and local verification commands.
Read `COMPONENTS.md` for the generated protocol flow, framework touchpoints and production gap.
Read `NEXT_STEPS.md` for promotion checklist and high-risk stop points.
Read `zero-scaffold.json` when a tool needs machine-readable scaffold metadata.

## Boundaries

- This project is a local / prototype scene-sync scaffold.
- It serializes scene state through a local Actor lane.
- It uses a small in-memory map and Chebyshev distance for visibility.
- It does not implement production AOI data structures, broadcast, delta compression, client snapshot protocol, path sync or cross-server migration.
- The default selection does not connect external middleware or open network ports. Adding Redis requires an external service at startup.
- It is not a production AOI or state-sync API commitment.
