# __PROJECT_NAME__

This local game project was generated by zeroServer `scripts/NewLocalGame.java`.

## Run

First install the current zeroServer SNAPSHOT into the local Maven repository:

~~~powershell
mvn -q -DskipTests install
~~~

Then run these commands in this project directory:

~~~powershell
mvn -q clean test
mvn -q exec:java
~~~

Expected output:

~~~text
local-game=ok|mode=local|name=__PROJECT_NAME__|uid=1001|position=3,5|logs=4|metrics=2|maxProtocolId=90105
~~~

## Layout

~~~text
src/main/protocol/Game.si
src/main/protocol/protoId.txt
src/main/java/__PACKAGE_PATH__/__APP_CLASS__.java
src/main/java/__PACKAGE_PATH__/LocalGameBO.java
src/main/java/__PACKAGE_PATH__/LocalGameFlow.java
src/main/java/__PACKAGE_PATH__/LocalGameFixture.java
src/main/java/__PACKAGE_PATH__/LocalGameObservation.java
src/test/java/__PACKAGE_PATH__/__TEST_CLASS__.java
src/test/java/__PACKAGE_PATH__/LocalGameAsyncTest.java
BUSINESS_GUIDE.md
COMPONENTS.md
NEXT_STEPS.md
zero-scaffold.json
~~~

The Maven `generate-sources` phase calls `zero-codegen` and writes generated protocol sources to:

~~~text
target/generated-sources/zero-codegen
~~~

## Optional TCP Server

Only projects generated with `--components net` contain `__SERVER_CLASS__` and the smoke helper `__CLIENT_CLASS__`. The generated composition enables the selected network lifecycle provider with a handshake-rejecting placeholder policy and the framework bounded rate limiter. Supply application handshake, authentication and security-chain behavior before using this composition for real clients. The separate Server example is for local loopback echo only. The intended server command is:

~~~powershell
mvn -q exec:java '-Dexec.mainClass=__PACKAGE__.__SERVER_CLASS__' '-Dexec.args=--port=0 --once'
~~~

This binds a loopback ephemeral port, sends a real TCP smoke request and closes resources. Remove `--once` and use `--port=6200` to keep listening; Ctrl+C stops the server. The client helper has no standalone main method. The response is a minimal request DTO echo, not a complete login response protocol. Authentication, TLS, heartbeat, rate limiting and production capacity remain application responsibilities.

## Async Boundary

`LocalGameBO`, `LocalGameFlow`, `LocalGameFixture` and `LocalGameObservation` are separate generated files. Business services return `CompletionStage`; handler and Actor paths must never call `join()` or `get()`. The single wait retained in `__APP_CLASS__.java` is only the outer `runDemo` smoke boundary. `runDemo` is not a long-running production server.

## Next Business Step

After the first run, open `BUSINESS_GUIDE.md` and follow `First Business Change` before adding broader systems.

## Components

Read `BUSINESS_GUIDE.md` for business editing points, protocol changes and local verification commands.
Read `COMPONENTS.md` for the generated protocol flow, framework touchpoints and production gap.
Read `NEXT_STEPS.md` for promotion checklist and high-risk stop points.
Read `zero-scaffold.json` when a tool needs machine-readable scaffold metadata.

## Boundaries

- This project is a local / prototype scaffold.
- The default selection does not connect external middleware. Adding Redis requires an external service at startup.
- The default demo does not open network ports. Selecting `net` also generates the explicit Server entry described below.
- It does not include account authentication, AOI, broadcast, frame sync, GM security or production deployment config.
