# __PROJECT_NAME__

This local game project was generated by zeroServer `scripts/NewLocalGame.java`.

## Run

First install the current zeroServer SNAPSHOT into the local Maven repository:

~~~powershell
mvn -q -DskipTests install
~~~

Then run these commands in this project directory:

~~~powershell
mvn -q clean test
mvn -q exec:java
~~~

Expected output:

~~~text
local-game=ok|mode=local|name=__PROJECT_NAME__|uid=1001|position=3,5|logs=4|metrics=2|maxProtocolId=90105
~~~

## Layout

~~~text
src/main/protocol/Game.si
src/main/protocol/protoId.txt
src/main/java/__PACKAGE_PATH__/__APP_CLASS__.java
src/test/java/__PACKAGE_PATH__/__TEST_CLASS__.java
BUSINESS_GUIDE.md
COMPONENTS.md
NEXT_STEPS.md
zero-scaffold.json
~~~

The Maven `generate-sources` phase calls `zero-codegen` and writes generated protocol sources to:

~~~text
target/generated-sources/zero-codegen
~~~

## Next Business Step

After the first run, open `BUSINESS_GUIDE.md` and follow `First Business Change` before adding broader systems.

## Components

Read `BUSINESS_GUIDE.md` for business editing points, protocol changes and local verification commands.
Read `COMPONENTS.md` for the generated protocol flow, framework touchpoints and production gap.
Read `NEXT_STEPS.md` for promotion checklist and high-risk stop points.
Read `zero-scaffold.json` when a tool needs machine-readable scaffold metadata.

## Boundaries

- This project is a local / prototype scaffold.
- The default selection does not connect external middleware. Adding Redis requires an external service at startup.
- It does not open network ports.
- It does not include account authentication, AOI, broadcast, frame sync, GM security or production deployment config.
