package group.zn.zero.codegen;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import group.zn.zero.codegen.dsl.SiProtocolProjectParser;
import group.zn.zero.codegen.error.CodegenErrorCode;
import group.zn.zero.codegen.model.CodegenLanguage;
import group.zn.zero.codegen.model.CodegenRequest;
import group.zn.zero.core.error.ZeroException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.FileTime;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * 重生成必须保留业务实现与未改变的文件，同时继续保护非生成源码。
 *
 * @author zn
 */
class CodegenRegenerationTest {

    /** 独占测试目录。 */
    @TempDir private Path root;

    /** 四种语言相同生成结果均不改变文件内容与时间戳。 */
    @Test
    void unchangedOutputsShouldKeepModificationTimesForEveryLanguage() throws Exception {
        var generator = new DefaultCodeGenerator();
        var request = request(List.of(CodegenLanguage.values()), "long uid");
        generator.generate(request);
        Map<Path, String> contents = new LinkedHashMap<>();
        Map<Path, FileTime> times = new LinkedHashMap<>();
        for (Path file : outputs(request)) {
            contents.put(file, Files.readString(file));
            Files.setLastModifiedTime(file, FileTime.from(Instant.parse("2020-01-01T00:00:00Z")));
            times.put(file, Files.getLastModifiedTime(file));
        }
        assertTrue(contents.size() > 15);
        generator.generate(request);
        assertEquals(contents.size(), outputs(request).size());
        for (Path file : contents.keySet()) {
            assertEquals(contents.get(file), Files.readString(file));
            assertEquals(times.get(file), Files.getLastModifiedTime(file), file.toString());
        }
    }

    /** 新旧模板标记均不能导致业务实现被重生成覆盖；DTO 和接口继续更新。 */
    @Test
    void regenerationShouldPreserveBothLegacyAndUserOwnedImplementations() throws Exception {
        var generator = new DefaultCodeGenerator();
        var initial = request(List.of(CodegenLanguage.JAVA), "long uid");
        generator.generate(initial);
        Path base = initial.outputDir().resolve("group/zn/zero/generated");
        Path legacy = base.resolve("bo/impl/PlayerQueryEventBOImp.java");
        Path owned = base.resolve("bo/impl/PlayerPingEventBOImp.java");
        assertFalse(Files.readString(legacy).contains("Do not edit manually"));
        String legacyContent = Files.readString(legacy).replace(
                "Created by zeroServer codegen. User-owned implementation; edit as needed.",
                "Generated by zeroServer codegen. Do not edit manually.") + "\n// existing business logic\n";
        String ownedContent = Files.readString(owned) + "\n// user business logic\n";
        Files.writeString(legacy, legacyContent);
        Files.writeString(owned, ownedContent);
        generator.generate(request(List.of(CodegenLanguage.JAVA), "long uid, String traceId"));
        assertEquals(legacyContent, Files.readString(legacy));
        assertEquals(ownedContent, Files.readString(owned));
        assertTrue(Files.readString(base.resolve("dto/PlayerQueryProtocolDTO.java")).contains("traceId"));
        assertTrue(Files.readString(base.resolve("dto/codec/PlayerQueryProtocolDTOCodec.java")).contains("traceId"));
    }

    /** 各语言输出遇到没有生成标记的文件时拒绝覆盖并保留其内容。 */
    @Test
    void everyLanguageShouldStillRejectOverwritingNonGeneratedSources() throws Exception {
        for (CodegenLanguage language : CodegenLanguage.values()) {
            var generator = new DefaultCodeGenerator();
            var request = request(List.of(language), "long uid");
            generator.generate(request);
            Path protectedFile = outputs(request).stream()
                    .filter(path -> !path.getFileName().toString().endsWith("Imp.java"))
                    .findFirst().orElseThrow();
            Files.writeString(protectedFile, "// handwritten source\n");
            ZeroException error = assertThrows(ZeroException.class, () -> generator.generate(request));
            assertEquals(CodegenErrorCode.OUTPUT_FAILED.code(), error.code());
            assertEquals("// handwritten source\n", Files.readString(protectedFile));
        }
    }

    private CodegenRequest request(final List<CodegenLanguage> languages, final String fields) throws Exception {
        Path dsl = root.resolve("Player.si");
        Files.writeString(dsl, "client_to_server:\n  query(" + fields + ");\n  ping();\n");
        var document = new SiProtocolProjectParser().parse("group.zn.zero.generated", List.of(dsl), null);
        Path output = root.resolve("output-" + languages);
        return new CodegenRequest(document, output, languages, true);
    }

    private List<Path> outputs(final CodegenRequest request) throws Exception {
        try (Stream<Path> files = Files.walk(request.outputDir())) {
            return files.filter(Files::isRegularFile).sorted().toList();
        }
    }
}
