package group.zn.zero.codegen.generator;

import group.zn.zero.codegen.error.CodegenErrorCode;
import group.zn.zero.core.error.ZeroException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

/**
 * 统一管理协议生成源码与业务实现模板的写入策略；同一输出目录由调用方串行生成。
 *
 * @author zn
 */
public final class GeneratedSourceWriter {

    /** 工具管理的源码标记。 */
    private static final String GENERATED_MARKER = "Generated by zeroServer codegen";

    private GeneratedSourceWriter() {
    }

    /**
     * 更新工具管理的源码；内容一致时保留文件及修改时间，不删除任何文件。
     *
     * @param path 输出文件，不可为空。
     * @param content UTF-8 源码，不可为空。
     * @throws ZeroException 文件没有生成标记或读写失败；绑定 OUTPUT_FAILED。
     */
    public static void writeGenerated(final Path path, final String content) {
        try {
            validateGenerated(path);
            if (Files.isRegularFile(path)) {
                String existing = Files.readString(path, StandardCharsets.UTF_8);
                if (existing.equals(content)) {
                    return;
                }
            }
            createParent(path);
            Files.writeString(path, content, StandardCharsets.UTF_8);
        } catch (IOException ex) {
            throw outputFailure(path, ex);
        }
    }

    /**
     * 首次创建业务实现模板，已有普通文件始终保留，包括保留旧生成标记的业务代码。
     *
     * @param path 输出文件，不可为空。
     * @param content UTF-8 模板，不可为空。
     * @throws ZeroException 目标不是普通文件或创建失败；绑定 OUTPUT_FAILED。
     */
    public static void createImplementation(final Path path, final String content) {
        try {
            validateImplementation(path);
            createParent(path);
            Files.writeString(path, content, StandardCharsets.UTF_8, StandardOpenOption.CREATE_NEW);
        } catch (FileAlreadyExistsException ex) {
            if (!Files.isRegularFile(path)) {
                throw outputFailure(path, ex);
            }
        } catch (IOException ex) {
            throw outputFailure(path, ex);
        }
    }

    /**
     * 检查目标是否属于工具管理，供整批生成预检使用。
     *
     * @param path 目标文件，不可为空。
     * @throws ZeroException 非生成文件、非普通文件或读取失败时抛出。
     */
    static void validateGenerated(final Path path) {
        validateParent(path);
        if (!Files.exists(path)) {
            return;
        }
        if (!Files.isRegularFile(path)) {
            throw ZeroException.of(CodegenErrorCode.OUTPUT_FAILED,
                    "generated output is not a regular file: " + path, null);
        }
        try {
            if (!Files.readString(path, StandardCharsets.UTF_8).contains(GENERATED_MARKER)) {
                throw ZeroException.of(CodegenErrorCode.OUTPUT_FAILED,
                        "refuse to overwrite non-generated file: " + path, null);
            }
        } catch (IOException ex) {
            throw outputFailure(path, ex);
        }
    }

    /**
     * 检查已有业务实现可被安全保留，供整批生成预检使用。
     *
     * @param path 目标文件，不可为空。
     * @throws ZeroException 目标或上级路径类型错误时抛出。
     */
    static void validateImplementation(final Path path) {
        validateParent(path);
        if (Files.exists(path) && !Files.isRegularFile(path)) {
            throw ZeroException.of(CodegenErrorCode.OUTPUT_FAILED,
                    "implementation output is not a regular file: " + path, null);
        }
    }

    private static void validateParent(final Path path) {
        for (Path parent = path.toAbsolutePath().normalize().getParent(); parent != null; parent = parent.getParent()) {
            if (Files.exists(parent) && !Files.isDirectory(parent)) {
                throw ZeroException.of(CodegenErrorCode.OUTPUT_FAILED,
                        "generated output parent is not a directory: " + parent, null);
            }
        }
    }

    private static void createParent(final Path path) throws IOException {
        Path parent = path.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
    }

    private static ZeroException outputFailure(final Path path, final IOException cause) {
        return ZeroException.of(CodegenErrorCode.OUTPUT_FAILED, "failed to write generated file: " + path, cause);
    }
}
