package group.zn.zero.codegen.generator;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;

/** 输出存储底层能力：路径检查、摘要和同目录原子替换，不依赖模板或 CLI。 */
final class OutputFiles {
    /** 首次接管现有生成物时要求的标记。 */
    static final String MARKER = "Generated by zeroServer codegen";

    private OutputFiles() {
    }

    /** 拒绝链接和非普通目标，避免跟随链接写出显式目录。 */
    static void validate(final Path path) throws IOException {
        for (Path parent = path; parent != null; parent = parent.getParent()) {
            if (Files.isSymbolicLink(parent)) {
                throw new IOException("output path must not contain symbolic links: " + parent);
            }
            if (Files.exists(parent) && !(parent.equals(path) ? Files.isRegularFile(parent) : Files.isDirectory(parent))) {
                throw new IOException("invalid output path: " + parent);
            }
        }
    }

    /** 单次读取当前内容；不存在返回 null。 */
    static String read(final Path path) throws IOException {
        validate(path);
        return Files.exists(path) ? Files.readString(path) : null;
    }

    /** SHA-256 内容摘要；空引用代表文件不存在。 */
    static String hash(final String text) {
        if (text == null) {
            return "";
        }
        try {
            return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException ex) {
            throw new IllegalStateException("JDK SHA-256 unavailable", ex);
        }
    }

    /** 完整写入同目录临时文件后替换，null 内容表示删除一个已预检的文件。 */
    static void replace(final Path path, final String content) throws IOException {
        validate(path);
        if (content == null) {
            Files.deleteIfExists(path);
            return;
        }
        Files.createDirectories(path.getParent());
        Path temporary = Files.createTempFile(path.getParent(), ".zero-codegen-", ".tmp");
        try {
            Files.writeString(temporary, content);
            try {
                Files.move(temporary, path, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
            } catch (AtomicMoveNotSupportedException ex) {
                Files.move(temporary, path, StandardCopyOption.REPLACE_EXISTING);
            }
        } finally {
            Files.deleteIfExists(temporary);
        }
    }
}
