# __PROJECT_NAME__

This local NPC tick project was generated by zeroServer `scripts/NewLocalGame.java --template npc-tick`.

## Run

First install the current zeroServer SNAPSHOT into the local Maven repository:

~~~powershell
mvn -q -DskipTests install
~~~

Then run these commands in this project directory:

~~~powershell
mvn -q clean test
mvn -q exec:java
~~~

Expected output:

~~~text
npc-tick=ok|mode=local|name=__PROJECT_NAME__|summary=zone=zone-1,npcs=1,npc=2001,behavior=idle,position=12,10,tick=3,updates=7,lastAction=query:2001@12,10|logs=8|metrics=7|maxProtocolId=94107
~~~

## Layout

~~~text
src/main/protocol/NpcTick.si
src/main/protocol/protoId.txt
src/main/java/__PACKAGE_PATH__/__APP_CLASS__.java
src/test/java/__PACKAGE_PATH__/__TEST_CLASS__.java
BUSINESS_GUIDE.md
COMPONENTS.md
NEXT_STEPS.md
zero-scaffold.json
~~~

The Maven `generate-sources` phase calls `zero-codegen` and writes generated NPC tick protocol sources to:

~~~text
target/generated-sources/zero-codegen
~~~

## Next Business Step

After the first run, open `BUSINESS_GUIDE.md` and follow `First Business Change` before adding broader systems.

## Components

Read `BUSINESS_GUIDE.md` for business editing points, protocol changes and local verification commands.
Read `COMPONENTS.md` for the generated protocol flow, framework touchpoints and production gap.
Read `NEXT_STEPS.md` for promotion checklist and high-risk stop points.
Read `zero-scaffold.json` when a tool needs machine-readable scaffold metadata.

## Boundaries

- This project is a local / prototype NPC tick scaffold.
- It serializes zone state through a local Actor lane.
- It demonstrates NPC spawn, behavior switch, deterministic local ticks and state query only.
- It does not implement behavior trees, pathfinding, combat AI, aggro, tick budget, backpressure or cross-server migration.
- The default selection does not connect external middleware or open network ports. Adding Redis requires an external service at startup.
- It is not a production NPC / AI / tick API commitment.
