package group.zn.zero.codegen.generator;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;

import group.zn.zero.codegen.error.CodegenErrorCode;
import group.zn.zero.core.error.ZeroException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * 整批协议输出计划的冲突及归属测试。
 *
 * @author zn
 */
class GeneratedOutputPlanTest {

    /** 测试独占输出目录。 */
    @TempDir
    private Path root;

    /** 后续目标冲突时，已经计划的生成文件仍保持原内容。 */
    @Test
    void lateOwnershipConflictShouldLeaveAllOutputsUntouched() throws Exception {
        Path generated = root.resolve("java/Packet.java");
        Path protectedFile = root.resolve("typescript/packet.ts");
        Files.createDirectories(generated.getParent());
        Files.createDirectories(protectedFile.getParent());
        Files.writeString(generated, "// Generated by zeroServer codegen\nold");
        Files.writeString(protectedFile, "// handwritten\n");

        GeneratedOutputPlan plan = new GeneratedOutputPlan();
        plan.addGenerated(generated, "// Generated by zeroServer codegen\nnew");
        plan.addGenerated(protectedFile, "// Generated by zeroServer codegen\nnew");

        ZeroException error = assertThrows(ZeroException.class, plan::apply);
        assertEquals(CodegenErrorCode.OUTPUT_FAILED.code(), error.code());
        assertEquals("// Generated by zeroServer codegen\nold", Files.readString(generated));
        assertEquals("// handwritten\n", Files.readString(protectedFile));
    }

    /** 目标重复或一个目标占用另一个目标的目录时，应在写盘前拒绝。 */
    @Test
    void collidingPathsShouldBeRejectedBeforeWriting() {
        GeneratedOutputPlan plan = new GeneratedOutputPlan();
        Path target = root.resolve("java/Packet.java");
        plan.addGenerated(target, "generated");

        assertThrows(ZeroException.class, () -> plan.addImplementation(target, "implementation"));
        assertThrows(ZeroException.class, () -> plan.addGenerated(target.resolve("Child.java"), "child"));
        assertThrows(ZeroException.class, () -> plan.addGenerated(root.resolve("java"), "parent"));
        assertFalse(Files.exists(target));
    }

    /** 登记失败不得污染目录索引，后续合法目标仍可使用原计划。 */
    @Test
    void rejectedPathShouldNotChangeThePlan() throws Exception {
        GeneratedOutputPlan plan = new GeneratedOutputPlan();
        Path file = root.resolve("base/Packet.java");
        Path sibling = file.resolve("nested/Child.java");
        plan.addGenerated(file, "// Generated by zeroServer codegen\npacket");
        assertThrows(ZeroException.class, () -> plan.addGenerated(sibling, "child"));
        Path independent = root.resolve("other/Valid.java");
        plan.addGenerated(independent, "// Generated by zeroServer codegen\nvalid");
        plan.apply();
        assertEquals("// Generated by zeroServer codegen\nvalid", Files.readString(independent));
        assertFalse(Files.exists(sibling));
    }

    /** 已存在的业务实现无需生成标记且始终保留。 */
    @Test
    void existingImplementationShouldBePreserved() throws Exception {
        Path implementation = root.resolve("java/PacketBOImp.java");
        Files.createDirectories(implementation.getParent());
        Files.writeString(implementation, "custom business logic");

        GeneratedOutputPlan plan = new GeneratedOutputPlan();
        plan.addImplementation(implementation, "new template");
        plan.apply();

        assertEquals("custom business logic", Files.readString(implementation));
    }
}
