package group.zn.zero.codegen.generator;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import group.zn.zero.core.error.ZeroException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.channels.FileChannel;
import java.nio.channels.FileLock;
import java.nio.file.StandardOpenOption;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/** 清单归属、受控清理、并发编辑和中断恢复测试。 */
class ManagedOutputTest {
    /** 测试目录。 */
    @TempDir
    private Path root;
    /** 生成文件标记。 */
    private static final String HEADER = "// Generated by zeroServer codegen\n";

    @Test
    void staleFilesArePreviewedAndOnlyUnmodifiedOwnedFilesArePruned() throws Exception {
        Path old = root.resolve("Old.java");
        Path edited = root.resolve("Edited.java");
        Path implementation = root.resolve("OldBOImp.java");
        GeneratedOutputPlan initial = plan();
        initial.addGenerated(old, HEADER + "old");
        initial.addGenerated(edited, HEADER + "edited");
        initial.addImplementation(implementation, "business logic");
        initial.apply();
        Files.writeString(edited, HEADER + "hand edited");
        GeneratedOutputPlan updated = plan();
        updated.addGenerated(root.resolve("New.java"), HEADER + "new");
        assertTrue(updated.inspect().stream().anyMatch(c -> c.status().equals("stale")));
        updated.inspect(true);
        updated.apply();
        assertFalse(Files.exists(old));
        assertEquals(HEADER + "hand edited", Files.readString(edited));
        assertEquals("business logic", Files.readString(implementation));
    }

    @Test
    void manualEditsAndEditsAfterPreviewMustNotBeOverwritten() throws Exception {
        Path target = root.resolve("Packet.java");
        GeneratedOutputPlan initial = plan();
        initial.addGenerated(target, HEADER + "old");
        initial.apply();
        GeneratedOutputPlan updated = plan();
        updated.addGenerated(target, HEADER + "new");
        updated.inspect();
        Files.writeString(target, HEADER + "concurrent edit");
        assertThrows(ZeroException.class, updated::apply);
        assertThrows(ZeroException.class, updated::inspect);
        assertEquals(HEADER + "concurrent edit", Files.readString(target));
    }

    @Test
    void ioFailureRollsBackEarlierWrites() throws Exception {
        Path first = root.resolve("First.java");
        Path second = root.resolve("Second.java");
        Files.writeString(first, "before");
        OutputTransaction transaction = new OutputTransaction(root, path -> path.startsWith(root));
        List<OutputTransaction.Mutation> changes = List.of(
                new OutputTransaction.Mutation(first.toString(), "before", "after"),
                new OutputTransaction.Mutation(second.toString(), null, "created"));
        assertThrows(IOException.class, () -> transaction.apply(changes, index -> {
            if (index == 1) {
                throw new IOException("simulated disk failure");
            }
        }));
        assertEquals("before", Files.readString(first));
        assertFalse(Files.exists(second));
        assertFalse(Files.exists(root.resolve(OutputTransaction.JOURNAL)));
    }

    @Test
    void interruptedProcessCanRecoverButMustPreserveExternalEdits() throws Exception {
        Path file = root.resolve("Packet.java");
        OutputTransaction transaction = new OutputTransaction(root, path -> path.startsWith(root));
        List<OutputTransaction.Mutation> changes = List.of(
                new OutputTransaction.Mutation(file.toString(), null, "new"),
                new OutputTransaction.Mutation(root.resolve("Other.java").toString(), null, "other"));
        assertThrows(AssertionError.class, () -> transaction.apply(changes, index -> {
            if (index == 1) {
                throw new AssertionError("simulate process termination without catch/rollback");
            }
        }));
        assertEquals("new", Files.readString(file));
        Files.writeString(file, "user edit");
        assertThrows(IOException.class, transaction::recover);
        assertEquals("user edit", Files.readString(file));
        assertTrue(Files.exists(root.resolve(OutputTransaction.JOURNAL)));
        Files.writeString(file, "new");
        transaction.recover();
        assertFalse(Files.exists(file));
        assertFalse(Files.exists(root.resolve(OutputTransaction.JOURNAL)));
    }

    private GeneratedOutputPlan plan() {
        return new GeneratedOutputPlan(root, List.of(root));
    }

    @Test
    void concurrentWriterLockShouldRejectBeforeWriting() throws Exception {
        Path target = root.resolve("Packet.java");
        GeneratedOutputPlan plan = plan();
        plan.addGenerated(target, HEADER + "new");
        try (FileChannel channel = FileChannel.open(root.resolve(".zero-codegen.lock"),
                StandardOpenOption.CREATE, StandardOpenOption.WRITE); FileLock held = channel.lock()) {
            assertTrue(held.isValid());
            assertThrows(ZeroException.class, plan::apply);
        }
        assertFalse(Files.exists(target));
        assertFalse(Files.exists(root.resolve(OutputTransaction.JOURNAL)));
    }
}
