<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>group.zn.zero</groupId><artifactId>zero-parent</artifactId><version>0.1.0-SNAPSHOT</version><relativePath>../zero-parent/pom.xml</relativePath></parent><artifactId>zero-ranking</artifactId><name>zeroServer Ranking</name><dependencies><dependency><groupId>group.zn.zero</groupId><artifactId>zero-actor</artifactId></dependency></dependencies></project>
