package group.zn.zero.npc;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
public final class LocalNpcZone { private final ZoneActor actor; private final Map<NpcId,NpcSnapshot> npcs=new LinkedHashMap<>(); private final BehaviorAdapter adapter; private final NpcEventSink events; private final NpcAuditSink audit; private final NpcMetrics metrics;
 public LocalNpcZone(ZoneActor a,BehaviorAdapter b,NpcEventSink e,NpcAuditSink au,NpcMetrics m){actor=Objects.requireNonNull(a);adapter=Objects.requireNonNull(b);events=Objects.requireNonNull(e);audit=Objects.requireNonNull(au);metrics=Objects.requireNonNull(m);}
 public NpcSnapshot spawn(NpcSnapshot n){if(n.lifecycle()!=NpcLifecycleState.CREATED)throw new IllegalArgumentException("NPC must be CREATED");NpcSnapshot x=new NpcSnapshot(n.npcId(),n.templateId(),actor.zoneId(),n.sceneId(),actor.zoneId(),NpcLifecycleState.ACTIVE,n.behavior(),n.version()+1,n.spawnedAt(),n.lastTickAt(),n.traceId());npcs.put(x.npcId(),x);events.publish(new NpcEvent(actor.zoneId(),x.npcId(),NpcEvent.Type.SPAWNED,x.version(),x.traceId()));audit.record(new NpcAuditEvent("spawn",actor.zoneId(),x.npcId(),x.traceId()));metrics.recordSpawn();return x;}
 public NpcSnapshot despawn(NpcId id,String trace){NpcSnapshot n=Objects.requireNonNull(npcs.remove(id));NpcSnapshot x=new NpcSnapshot(n.npcId(),n.templateId(),n.zoneId(),n.sceneId(),n.ownerActorId(),NpcLifecycleState.REMOVED,n.behavior(),n.version()+1,n.spawnedAt(),n.lastTickAt(),trace);events.publish(new NpcEvent(actor.zoneId(),id,NpcEvent.Type.DESPAWNED,x.version(),trace));audit.record(new NpcAuditEvent("despawn",actor.zoneId(),id,trace));metrics.recordDespawn();return x;}
 public TickResult tick(TickBudget budget,String trace){int candidates=npcs.size(),done=0,skip=0;long start=System.nanoTime();for(NpcSnapshot n:new ArrayList<>(npcs.values())){if(done>=budget.budgetOps()){skip++;continue;}try{BehaviorDecision d=adapter.decide(n,new BehaviorContext(actor.zoneId(),done+1,trace));if(!d.nextState().equals(n.behavior())){npcs.put(n.npcId(),new NpcSnapshot(n.npcId(),n.templateId(),n.zoneId(),n.sceneId(),n.ownerActorId(),n.lifecycle(),d.nextState(),n.version()+1,n.spawnedAt(),System.currentTimeMillis(),trace));events.publish(new NpcEvent(actor.zoneId(),n.npcId(),NpcEvent.Type.BEHAVIOR_CHANGED,n.version()+1,trace));}done++;}catch(Exception ex){events.publish(new NpcEvent(actor.zoneId(),n.npcId(),NpcEvent.Type.BEHAVIOR_FAILED,n.version(),trace));metrics.recordBehaviorFailure(actor.zoneId(),n.behavior().type());done++;}if((System.nanoTime()-start)/1_000_000>=budget.budgetMillis()){skip+=candidates-done;break;}}TickResult.Outcome o=skip==0?TickResult.Outcome.COMPLETED:(done==0?TickResult.Outcome.SKIPPED:TickResult.Outcome.DEGRADED);TickResult r=new TickResult(actor.zoneId(),candidates,done,skip,o);metrics.recordTick(r);return r;}
 public Optional<NpcSnapshot> find(NpcId id){return Optional.ofNullable(npcs.get(id));} public int size(){return npcs.size();}
}
