# __PROJECT_NAME__

This local room project was generated by zeroServer `scripts/NewLocalGame.java --template room`.

## Run

First install the current zeroServer SNAPSHOT into the local Maven repository:

~~~powershell
mvn -q -DskipTests install
~~~

Then run these commands in this project directory:

~~~powershell
mvn -q clean test
mvn -q exec:java
~~~

Expected output:

~~~text
room-game=ok|mode=local|name=__PROJECT_NAME__|summary=room=room-1,owner=1001,players=2,ready=2,started=true,frame=1,inputSum=42|logs=7|metrics=6|maxProtocolId=91109
~~~

## Layout

~~~text
src/main/protocol/Room.si
src/main/protocol/protoId.txt
src/main/java/__PACKAGE_PATH__/__APP_CLASS__.java
src/test/java/__PACKAGE_PATH__/__TEST_CLASS__.java
BUSINESS_GUIDE.md
COMPONENTS.md
NEXT_STEPS.md
zero-scaffold.json
~~~

The Maven `generate-sources` phase calls `zero-codegen` and writes generated room protocol sources to:

~~~text
target/generated-sources/zero-codegen
~~~

## Next Business Step

After the first run, open `BUSINESS_GUIDE.md` and follow `First Business Change` before adding broader systems.

## Components

Read `BUSINESS_GUIDE.md` for business editing points, protocol changes and local verification commands.
Read `COMPONENTS.md` for the generated protocol flow, framework touchpoints and production gap.
Read `NEXT_STEPS.md` for promotion checklist and high-risk stop points.
Read `zero-scaffold.json` when a tool needs machine-readable scaffold metadata.

## Boundaries

- This project is a local / prototype room scaffold.
- It serializes room state through a local Actor lane.
- It does not implement matchmaking, broadcast, disconnect recovery, spectators, frame sync or cross-server migration.
- The default selection does not connect external middleware or open network ports. Adding Redis requires an external service at startup.
- It is not a production room API commitment.
