package group.zn.zero.codegen.generator.client;

import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.TemplateException;
import freemarker.template.TemplateExceptionHandler;
import group.zn.zero.codegen.error.CodegenErrorCode;
import group.zn.zero.codegen.model.CodegenLanguage;
import group.zn.zero.codegen.model.CodegenRequest;
import group.zn.zero.core.error.ZeroException;
import java.io.IOException;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * 客户端模板渲染器基类。
 *
 * @author zn
 */
public abstract class AbstractTemplateCodegenRenderer {

    /**
     * FreeMarker 模板配置。
     */
    private final Configuration configuration;

    /**
     * 创建模板渲染器。
     *
     * @param templateRoot 模板根目录；不可为空。
     */
    protected AbstractTemplateCodegenRenderer(final String templateRoot) {
        configuration = new Configuration(Configuration.VERSION_2_3_34);
        configuration.setDefaultEncoding(StandardCharsets.UTF_8.name());
        configuration.setTemplateExceptionHandler(TemplateExceptionHandler.RETHROW_HANDLER);
        configuration.setLogTemplateExceptions(false);
        configuration.setWrapUncheckedExceptions(true);
        configuration.setClassLoaderForTemplateLoading(
                Thread.currentThread().getContextClassLoader(),
                templateRoot);
    }

    /**
     * 渲染模板。
     *
     * @param templateName 模板名称；不可为空。
     * @param model 模板数据模型；不可为空。
     * @return 渲染后的内容；不可为空；线程安全。
     * @throws ZeroException 模板渲染失败时抛出，必须绑定 ErrorCode。
     */
    protected String renderTemplate(final String templateName, final Map<String, Object> model) {
        try {
            Template template = configuration.getTemplate(templateName);
            StringWriter writer = new StringWriter(4096);
            template.process(model, writer);
            return writer.toString();
        } catch (IOException | TemplateException ex) {
            throw ZeroException.of(
                    CodegenErrorCode.OUTPUT_FAILED,
                    "failed to render template: " + templateName,
                    ex);
        }
    }

    /**
     * 基础模板模型。
     *
     * @param namespace 命名空间；不可为空。
     * @param classPrefix 类名前缀；不可为空。
     * @return 模板模型；不可为空；线程安全。
     */
    protected Map<String, Object> baseModel(final String namespace, final String classPrefix) {
        Map<String, Object> model = new LinkedHashMap<>();
        model.put("generatedMarker", "Generated by zeroServer codegen");
        model.put("namespace", namespace);
        model.put("packageName", namespace);
        model.put("classPrefix", classPrefix);
        model.put("imports", List.of());
        return model;
    }

    /**
     * 返回某语言在目标请求中的输出根目录。
     *
     * @param request 代码生成请求；不可为空。
     * @param language 目标语言；不可为空。
     * @return 输出根目录；不可为空；线程安全。
     */
    protected Path languageRoot(final CodegenRequest request, final CodegenLanguage language) {
        return request.outputDir(language).resolve(ClientCodegenSupport.packagePath(request.namespace(language)));
    }

    /**
     * 写入生成文件。
     *
     * @param path 输出路径；不可为空。
     * @param content 文件内容；不可为空。
     * @throws ZeroException 写文件失败时抛出，必须绑定 ErrorCode。
     */
    protected void writeGeneratedFile(final Path path, final String content) {
        try {
            Path parent = path.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            if (Files.exists(path)) {
                String existing = Files.readString(path, StandardCharsets.UTF_8);
                if (!existing.contains("Generated by zeroServer codegen")) {
                    throw ZeroException.of(
                            CodegenErrorCode.OUTPUT_FAILED,
                            "refuse to overwrite non-generated file: " + path,
                            null);
                }
            }
            Files.writeString(path, content, StandardCharsets.UTF_8);
        } catch (IOException ex) {
            throw ZeroException.of(CodegenErrorCode.OUTPUT_FAILED, "failed to write generated file: " + path, ex);
        }
    }
}
