/*
 * Generated by zeroServer codegen. Do not edit manually.
 */
package group.zn.zero.protocol.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
/**
 * PlayerInfo 协议消息。
 */
public final class PlayerInfo implements Serializable {

    /**
     * 序列化版本。
     */
    private static final long serialVersionUID = 1L;

    /**
     * uid
     */
    public long uid;

    /**
     * name
     */
    public String name = "";

    /**
     * level
     */
    public int level;

    /**
     * role
     */
    public PlayerRole role;

    /**
     * tags
     */
    public List<Map<String, Integer>> tags = new ArrayList<>();

    /**
     * matrix
     */
    public int[][] matrix = new int[0][];

    /**
     * itemBuckets
     */
    public List<PlayerItem>[] itemBuckets;

    /**
     * title
     */
    public String title = null;
}
