/*
 * Generated by zeroServer codegen. Do not edit manually.
 */
package group.zn.zero.protocol.dto;

import java.io.Serializable;
/**
 * PlayerItem 协议消息。
 */
public final class PlayerItem implements Serializable {

    /**
     * 序列化版本。
     */
    private static final long serialVersionUID = 1L;

    /**
     * itemId
     */
    public long itemId;

    /**
     * count
     */
    public int count;
}
