/*
 * Generated by zeroServer codegen. Do not edit manually.
 */
package group.zn.zero.protocol.dto;

/**
 * PlayerRole 协议枚举。
 */
public enum PlayerRole {
    /**
     * UNKNOWN
     */
    UNKNOWN(0),
    /**
     * WARRIOR
     */
    WARRIOR(1),
    /**
     * MAGE
     */
    MAGE(2);

    /**
     * 协议枚举线格式值。
     */
    private final int value;

    /**
     * 创建协议枚举。
     *
     * @param value 协议枚举线格式值。
     */
    PlayerRole(final int value) {
        this.value = value;
    }

    /**
     * 返回协议枚举线格式值。
     *
     * @return 线格式值；线程安全。
     */
    public int value() {
        return value;
    }

    /**
     * 按线格式值查找枚举。
     *
     * @param value 线格式值。
     * @return 协议枚举；不可为空；线程安全。
     * @throws IllegalArgumentException 当枚举值未知时抛出。
     */
    public static PlayerRole fromValue(final int value) {
        for (PlayerRole item : values()) {
            if (item.value == value) {
                return item;
            }
        }
        throw new IllegalArgumentException("unknown PlayerRole value: " + value);
    }
}
