<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>group.zn.zero</groupId>
        <artifactId>zero-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
        <relativePath>../zero-parent/pom.xml</relativePath>
    </parent>

    <artifactId>zero-discovery-nacos</artifactId>
    <name>zeroServer Nacos Discovery Adapter</name>
    <description>Nacos 服务发现适配器模块。</description>

    <dependencies>
        <dependency>
            <groupId>group.zn.zero</groupId>
            <artifactId>zero-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>group.zn.zero</groupId>
            <artifactId>zero-rpc-discovery</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>group.zn.zero</groupId>
            <artifactId>zero-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>${nacos.client.version}</version>
        </dependency>
    </dependencies>
</project>
