# __PROJECT_NAME__

This local world shard project was generated by zeroServer `scripts/NewLocalGame.java --template world-shard`.

## Run

First install the current zeroServer SNAPSHOT into the local Maven repository:

~~~powershell
mvn -q -DskipTests install
~~~

Then run these commands in this project directory:

~~~powershell
mvn -q clean test
mvn -q exec:java
~~~

Expected output:

~~~text
world-shard=ok|mode=local|name=__PROJECT_NAME__|summary=world=world-1,shards=2,entities=2,entity=1001,shard=shard-b,position=54,4,migrations=1,lastAction=query:1001@shard-b|logs=7|metrics=6|maxProtocolId=96107
~~~

## Layout

~~~text
src/main/protocol/WorldShard.si
src/main/protocol/protoId.txt
src/main/java/__PACKAGE_PATH__/__APP_CLASS__.java
src/test/java/__PACKAGE_PATH__/__TEST_CLASS__.java
BUSINESS_GUIDE.md
COMPONENTS.md
NEXT_STEPS.md
zero-scaffold.json
~~~

The Maven `generate-sources` phase calls `zero-codegen` and writes generated world shard protocol sources to:

~~~text
target/generated-sources/zero-codegen
~~~

## Next Business Step

After the first run, open `BUSINESS_GUIDE.md` and follow `First Business Change` before adding broader systems.

## Components

Read `BUSINESS_GUIDE.md` for business editing points, protocol changes and local verification commands.
Read `COMPONENTS.md` for the generated protocol flow, framework touchpoints and production gap.
Read `NEXT_STEPS.md` for promotion checklist and high-risk stop points.
Read `zero-scaffold.json` when a tool needs machine-readable scaffold metadata.

## Boundaries

- This project is a local / prototype world shard scaffold.
- It serializes world and shard state through a local Actor lane.
- It demonstrates enter world, move, shard transfer and entity query only.
- It does not implement cross-process migration, reliable handoff, distributed locks, cross-server broadcast, AOI stitching or production consistency protocols.
- The default selection does not connect external middleware or open network ports. Adding Redis requires an external service at startup.
- It is not a production WorldShard / ScenePartition / migration API commitment.
