# __PROJECT_NAME__

This local frame sync project was generated by zeroServer `scripts/NewLocalGame.java --template frame-sync`.

## Run

First install the current zeroServer SNAPSHOT into the local Maven repository:

~~~powershell
mvn -q -DskipTests install
~~~

Then run these commands in this project directory:

~~~powershell
mvn -q clean test
mvn -q exec:java
~~~

Expected output:

~~~text
frame-sync=ok|mode=local|name=__PROJECT_NAME__|summary=match=match-1,players=2,frame=2,inputs=3,inputSum=17,snapshots=2|logs=9|metrics=8|maxProtocolId=93107
~~~

## Layout

~~~text
src/main/protocol/FrameSync.si
src/main/protocol/protoId.txt
src/main/java/__PACKAGE_PATH__/__APP_CLASS__.java
src/test/java/__PACKAGE_PATH__/__TEST_CLASS__.java
BUSINESS_GUIDE.md
COMPONENTS.md
NEXT_STEPS.md
zero-scaffold.json
~~~

The Maven `generate-sources` phase calls `zero-codegen` and writes generated frame-sync protocol sources to:

~~~text
target/generated-sources/zero-codegen
~~~

## Next Business Step

After the first run, open `BUSINESS_GUIDE.md` and follow `First Business Change` before adding broader systems.

## Components

Read `BUSINESS_GUIDE.md` for business editing points, protocol changes and local verification commands.
Read `COMPONENTS.md` for the generated protocol flow, framework touchpoints and production gap.
Read `NEXT_STEPS.md` for promotion checklist and high-risk stop points.
Read `zero-scaffold.json` when a tool needs machine-readable scaffold metadata.

## Boundaries

- This project is a local / prototype frame-sync scaffold.
- It serializes match state through a local Actor lane.
- It demonstrates fixed-frame input collection and snapshot summaries only.
- It does not implement network delay compensation, input resend, rollback, spectators, broadcast or cross-server migration.
- It does not connect external middleware or open network ports.
- It is not a production frame-sync API commitment.
