/*
 * Generated by zeroServer codegen. Do not edit manually.
 */
package group.zn.zero.protocol.codec;

import group.zn.zero.protocol.buffer.ZeroReader;
import group.zn.zero.protocol.buffer.ZeroWriter;
import group.zn.zero.protocol.codec.ZeroPayloadCodec;
import group.zn.zero.protocol.dto.PlayerInfo;
import group.zn.zero.protocol.dto.PlayerItem;
import group.zn.zero.protocol.dto.PlayerRole;

import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * PlayerInfo payload 编解码器。
 */
public final class PlayerInfoCodec implements ZeroPayloadCodec<PlayerInfo> {

    /**
     * 单例实例。
     */
    public static final PlayerInfoCodec INSTANCE = new PlayerInfoCodec();

    /**
     * 创建 payload 编解码器。
     */
    private PlayerInfoCodec() {
    }

    /**
     * 返回提供者名称。
     *
     * @return 提供者名称；不可为空；线程安全。
     */
    @Override
    public String name() {
        return "PlayerInfoCodec";
    }

    /**
     * 返回消息类型。
     *
     * @return 消息类型；不可为空；线程安全。
     */
    @Override
    public Class<PlayerInfo> messageType() {
        return PlayerInfo.class;
    }

    /**
     * 写入 payload。
     *
     * @param writer 写入器；不可为空。
     * @param message 消息；不可为空。
     * @throws NullPointerException 当写入器或消息为空时抛出。
     */
    @Override
    public void write(final ZeroWriter writer, final PlayerInfo message) {
        Objects.requireNonNull(writer, "writer");
        Objects.requireNonNull(message, "message");
        int objectMarker = writer.beginObject();
        writer.writePresenceBits(1, index -> switch (index) {
            case 0 -> message.title != null;
            default -> false;
        });
            writer.writeLong(message.uid);

            writer.writeString(message.name);

            writer.writeInt(message.level);

            writer.writeInt(Objects.requireNonNull(message.role, "message.role").value());

            writer.writeCollection(message.tags, (writerItemWriter, messagetagsItemValue) -> {
                writerItemWriter.writeMap(messagetagsItemValue, (writerItemWriterKeyWriter, messagetagsItemValueKeyValue) -> {
                    writerItemWriterKeyWriter.writeString(messagetagsItemValueKeyValue);
                }, (writerItemWriterValueWriter, messagetagsItemValueMapValue) -> {
                    writerItemWriterValueWriter.writeInt(messagetagsItemValueMapValue);
                });
            });

            writer.writeArray(message.matrix, (writerArrayWriter, messagematrixArrayValue) -> {
                writerArrayWriter.writeIntArray(messagematrixArrayValue);
            });

            writer.writeArray(message.itemBuckets, (writerArrayWriter, messageitemBucketsArrayValue) -> {
                writerArrayWriter.writeCollection(messageitemBucketsArrayValue, (writerArrayWriterItemWriter, messageitemBucketsArrayValueItemValue) -> {
                    PlayerItemCodec.INSTANCE.write(writerArrayWriterItemWriter, messageitemBucketsArrayValueItemValue);
                });
            });

        if (message.title != null) {
            writer.writeString(message.title);
        }

        writer.endObject(objectMarker);
    }

    /**
     * 读取 payload。
     *
     * @param reader 读取器；不可为空。
     * @return 消息；不可为空；线程不安全。
     * @throws NullPointerException 当读取器为空时抛出。
     */
    @Override
    @SuppressWarnings("unchecked")
    public PlayerInfo read(final ZeroReader reader) {
        Objects.requireNonNull(reader, "reader");
        int objectEnd = reader.beginObject();
        PlayerInfo message = new PlayerInfo();
        boolean[] presence = reader.hasRemainingInObject(objectEnd) ? reader.readPresenceBits() : new boolean[0];
        if (reader.hasRemainingInObject(objectEnd)) {
            message.uid = reader.readLong();
        }
        if (reader.hasRemainingInObject(objectEnd)) {
            message.name = reader.readString();
        }
        if (reader.hasRemainingInObject(objectEnd)) {
            message.level = reader.readInt();
        }
        if (reader.hasRemainingInObject(objectEnd)) {
            message.role = PlayerRole.fromValue(reader.readInt());
        }
        if (reader.hasRemainingInObject(objectEnd)) {
            message.tags = reader.readList(readerItemReader -> readerItemReader.readMap(readerItemReaderKeyReader -> readerItemReaderKeyReader.readString(), readerItemReaderValueReader -> readerItemReaderValueReader.readInt()));
        }
        if (reader.hasRemainingInObject(objectEnd)) {
            message.matrix = reader.readArray(int[].class, readerArrayReader -> readerArrayReader.readIntArray());
        }
        if (reader.hasRemainingInObject(objectEnd)) {
            message.itemBuckets = (List<PlayerItem>[]) reader.readArray(List.class, readerArrayReader -> readerArrayReader.readList(readerArrayReaderItemReader -> PlayerItemCodec.INSTANCE.read(readerArrayReaderItemReader)));
        }
        if (isPresent(presence, 0) && reader.hasRemainingInObject(objectEnd)) {
            message.title = reader.readString();
        }
        reader.endObject(objectEnd);
        return message;
    }

    /**
     * 判断 nullable 字段是否存在。
     *
     * @param presence presence 位图；不可为空。
     * @param index 字段序号。
     * @return true 表示字段在线格式中存在。
     */
    private static boolean isPresent(final boolean[] presence, final int index) {
        return index >= 0 && index < presence.length && presence[index];
    }
}
