/*
 * Generated by zeroServer codegen. Do not edit manually.
 */
package group.zn.zero.protocol.codec;

import group.zn.zero.protocol.buffer.ZeroReader;
import group.zn.zero.protocol.buffer.ZeroWriter;
import group.zn.zero.protocol.codec.ZeroPayloadCodec;
import group.zn.zero.protocol.dto.PlayerItem;

import java.util.Objects;

/**
 * PlayerItem payload 编解码器。
 */
public final class PlayerItemCodec implements ZeroPayloadCodec<PlayerItem> {

    /**
     * 单例实例。
     */
    public static final PlayerItemCodec INSTANCE = new PlayerItemCodec();

    /**
     * 创建 payload 编解码器。
     */
    private PlayerItemCodec() {
    }

    /**
     * 返回提供者名称。
     *
     * @return 提供者名称；不可为空；线程安全。
     */
    @Override
    public String name() {
        return "PlayerItemCodec";
    }

    /**
     * 返回消息类型。
     *
     * @return 消息类型；不可为空；线程安全。
     */
    @Override
    public Class<PlayerItem> messageType() {
        return PlayerItem.class;
    }

    /**
     * 写入 payload。
     *
     * @param writer 写入器；不可为空。
     * @param message 消息；不可为空。
     * @throws NullPointerException 当写入器或消息为空时抛出。
     */
    @Override
    public void write(final ZeroWriter writer, final PlayerItem message) {
        Objects.requireNonNull(writer, "writer");
        Objects.requireNonNull(message, "message");
        int objectMarker = writer.beginObject();
            writer.writeLong(message.itemId);

            writer.writeInt(message.count);

        writer.endObject(objectMarker);
    }

    /**
     * 读取 payload。
     *
     * @param reader 读取器；不可为空。
     * @return 消息；不可为空；线程不安全。
     * @throws NullPointerException 当读取器为空时抛出。
     */
    @Override
    public PlayerItem read(final ZeroReader reader) {
        Objects.requireNonNull(reader, "reader");
        int objectEnd = reader.beginObject();
        PlayerItem message = new PlayerItem();
        if (reader.hasRemainingInObject(objectEnd)) {
            message.itemId = reader.readLong();
        }
        if (reader.hasRemainingInObject(objectEnd)) {
            message.count = reader.readInt();
        }
        reader.endObject(objectEnd);
        return message;
    }
}
