package group.zn.zero.codegen.generator.java;

import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.TemplateException;
import freemarker.template.TemplateExceptionHandler;
import group.zn.zero.codegen.error.CodegenErrorCode;
import group.zn.zero.codegen.model.CodegenLanguage;
import group.zn.zero.codegen.model.CodegenRequest;
import group.zn.zero.codegen.model.JavaArtifactKind;
import group.zn.zero.codegen.model.ProtocolEnum;
import group.zn.zero.codegen.model.ProtocolEnumValue;
import group.zn.zero.codegen.model.ProtocolField;
import group.zn.zero.codegen.model.ProtocolMessage;
import group.zn.zero.codegen.model.ProtocolMethod;
import group.zn.zero.codegen.model.ProtocolType;
import group.zn.zero.codegen.model.ProtocolTypeKind;
import group.zn.zero.core.error.ZeroException;
import group.zn.zero.protocol.ProtocolDefinition;
import group.zn.zero.protocol.ProtocolFeature;
import java.io.IOException;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;

/**
 * 基于 FreeMarker 模板的 Java 代码生成渲染器。
 *
 * @author zn
 */
public final class JavaCodegenRenderer {

    /**
     * 生成文件标记。
     */
    private static final String GENERATED_MARKER = "Generated by zeroServer codegen";

    /**
     * 协议消息类后缀。
     */
    private static final String PROTOCOL_SUFFIX = "Protocol";

    /**
     * FreeMarker 模板配置。
     */
    private final Configuration configuration;

    /**
     * 类型映射器。
     */
    private final JavaTypeMapper typeMapper = new JavaTypeMapper();

    /**
     * 创建 Java 代码生成渲染器。
     */
    public JavaCodegenRenderer() {
        configuration = new Configuration(Configuration.VERSION_2_3_34);
        configuration.setDefaultEncoding(StandardCharsets.UTF_8.name());
        configuration.setTemplateExceptionHandler(TemplateExceptionHandler.RETHROW_HANDLER);
        configuration.setLogTemplateExceptions(false);
        configuration.setWrapUncheckedExceptions(true);
        configuration.setClassLoaderForTemplateLoading(
                Thread.currentThread().getContextClassLoader(),
                "/codegen/java");
    }

    /**
     * 渲染 Java 生成物。
     *
     * @param request 代码生成请求；不可为空。
     * @throws ZeroException 生成失败时抛出，必须绑定 ErrorCode。
     */
    public void render(final CodegenRequest request) {
        Objects.requireNonNull(request, "request");
        JavaLayout layout = JavaLayout.from(request);
        String dtoSuffix = request.dtoSuffix(CodegenLanguage.JAVA);
        JavaProjectModel project = new JavaProjectModel(request.document().messages());

        writeGeneratedFile(layout.dtoDir().resolve("ZeroGeneratedPayload.java"), renderTemplate("payloadMarker.java.ftl",
                baseModel(layout.dtoPackage())));
        for (ProtocolEnum item : request.document().enums()) {
            writeGeneratedFile(layout.dtoDir().resolve(item.name() + ".java"), renderTemplate("enum.java.ftl",
                    enumModel(layout.dtoPackage(), item)));
        }
        for (ProtocolMessage message : request.document().messages()) {
            String dtoName = dtoName(message.name(), dtoSuffix);
            writeGeneratedFile(layout.dtoDir().resolve(dtoName + ".java"), renderTemplate("message.java.ftl",
                    messageModel(layout.dtoPackage(), message, dtoSuffix)));
            writeGeneratedFile(layout.codecDir().resolve(dtoName + "Codec.java"),
                    renderTemplate("codec.java.ftl", codecModel(layout, message, project, dtoSuffix)));
        }
        writeGeneratedFile(layout.protocolDir().resolve("ProtocolIds.java"), renderTemplate("protocolIds.java.ftl",
                protocolIdsModel(layout.protocolPackage(), request.document().protocols())));
        writeGeneratedFile(layout.protocolDir().resolve("GeneratedProtocolDefinitions.java"),
                renderTemplate("protocolDefinitions.java.ftl",
                        protocolDefinitionsModel(layout.protocolPackage(), request.document().protocols())));
        renderBo(layout, request, dtoSuffix);
        renderDispatcher(layout, request, project, dtoSuffix);
    }

    private void renderBo(final JavaLayout layout, final CodegenRequest request, final String dtoSuffix) {
        Map<String, List<ProtocolMethod>> grouped = new LinkedHashMap<>();
        for (ProtocolMethod method : request.document().methods()) {
            grouped.computeIfAbsent(method.boName(), ignored -> new ArrayList<>()).add(method);
        }
        if (grouped.isEmpty()) {
            return;
        }
        for (Map.Entry<String, List<ProtocolMethod>> entry : grouped.entrySet()) {
            writeGeneratedFile(layout.boDir().resolve(entry.getKey() + ".java"), renderTemplate("boInterface.java.ftl",
                    boModel(layout, entry.getKey(), entry.getValue(), false, dtoSuffix)));
            if (request.generateBoImpl()) {
                String implName = implementationName(entry.getKey());
                writeGeneratedFile(layout.boImplDir().resolve(implName + ".java"), renderTemplate("boImpl.java.ftl",
                        boModel(layout, entry.getKey(), entry.getValue(), true, dtoSuffix)));
            }
        }
    }

    private void renderDispatcher(
            final JavaLayout layout,
            final CodegenRequest request,
            final JavaProjectModel project,
            final String dtoSuffix) {
        if (request.document().methods().isEmpty()) {
            return;
        }
        Path dispatcherPath = layout.dispatcherDir().resolve("GeneratedProtocolDispatcher.java");
        writeGeneratedFile(dispatcherPath, renderTemplate("dispatcher.java.ftl",
                dispatcherModel(layout, request.document().methods(), project, dtoSuffix)));
    }

    private Map<String, Object> enumModel(final String namespace, final ProtocolEnum item) {
        Map<String, Object> model = baseModel(namespace);
        model.put("name", item.name());
        model.put("comment", commentOrDefault(item.comment(), item.name() + " 协议枚举。"));
        List<Map<String, Object>> values = new ArrayList<>();
        for (ProtocolEnumValue value : item.values()) {
            Map<String, Object> valueModel = new LinkedHashMap<>();
            valueModel.put("name", value.name());
            valueModel.put("value", value.value());
            valueModel.put("comment", commentOrDefault(value.comment(), value.name()));
            values.add(valueModel);
        }
        model.put("values", values);
        return model;
    }

    private Map<String, Object> messageModel(
            final String namespace,
            final ProtocolMessage message,
            final String dtoSuffix) {
        Set<String> imports = new TreeSet<>();
        imports.add("java.io.Serializable");
        List<Map<String, Object>> fields = new ArrayList<>();
        for (ProtocolField field : message.fields()) {
            Map<String, Object> fieldModel = new LinkedHashMap<>();
            fieldModel.put("name", field.name());
            fieldModel.put("type", typeMapper.fieldType(field, imports, dtoSuffix));
            fieldModel.put("defaultValue", typeMapper.defaultValue(field, imports, dtoSuffix));
            fieldModel.put("comment", commentOrDefault(field.comment(), field.name()));
            fields.add(fieldModel);
        }

        Map<String, Object> model = baseModel(namespace);
        model.put("imports", List.copyOf(imports));
        model.put("name", dtoName(message.name(), dtoSuffix));
        model.put("comment", commentOrDefault(message.comment(), message.name() + " 协议消息。"));
        model.put("fields", fields);
        return model;
    }

    private Map<String, Object> protocolIdsModel(
            final String namespace,
            final List<ProtocolDefinition> protocols) {
        Map<String, Object> model = baseModel(namespace);
        List<Map<String, Object>> items = new ArrayList<>();
        int maxId = 0;
        for (ProtocolDefinition protocol : protocols) {
            Map<String, Object> item = new LinkedHashMap<>();
            item.put("constantName", constantName(protocol.name()));
            item.put("id", protocol.id());
            item.put("comment", protocol.name() + " 协议号。");
            items.add(item);
            maxId = Math.max(maxId, protocol.id());
        }
        model.put("items", items);
        model.put("maxId", maxId);
        return model;
    }

    private Map<String, Object> protocolDefinitionsModel(
            final String namespace,
            final List<ProtocolDefinition> protocols) {
        Map<String, Object> model = baseModel(namespace);
        model.put("imports", List.of(
                "group.zn.zero.protocol.ProtocolDefinition",
                "group.zn.zero.protocol.ProtocolDirection",
                "group.zn.zero.protocol.ProtocolFeature",
                "group.zn.zero.protocol.registry.ProtocolRegistry",
                "java.util.List",
                "java.util.Objects",
                "java.util.Set"));
        List<Map<String, Object>> items = new ArrayList<>();
        for (ProtocolDefinition protocol : protocols) {
            Map<String, Object> item = new LinkedHashMap<>();
            item.put("id", protocol.id());
            item.put("name", protocol.name());
            item.put("direction", protocol.direction().name());
            item.put("version", protocol.version());
            item.put("codecLiteral", codecLiteral(protocol));
            item.put("featuresLiteral", featureSet(protocol.features()));
            items.add(item);
        }
        model.put("protocols", items);
        return model;
    }

    private Map<String, Object> boModel(
            final JavaLayout layout,
            final String boName,
            final List<ProtocolMethod> methods,
            final boolean implementation,
            final String dtoSuffix) {
        String packageName = implementation ? layout.boImplPackage() : layout.boPackage();
        Set<String> imports = methodImports(packageName, layout.dtoPackage(), methods, dtoSuffix);
        if (implementation) {
            addImport(imports, packageName, layout.boPackage() + "." + boName);
        }
        Map<String, Object> model = baseModel(packageName);
        model.put("imports", List.copyOf(imports));
        model.put("boName", boName);
        model.put("implName", implementationName(boName));
        List<Map<String, Object>> items = new ArrayList<>();
        for (ProtocolMethod method : methods) {
            Map<String, Object> item = new LinkedHashMap<>();
            item.put("signature", methodSignature(method, dtoSuffix));
            item.put("comment", commentOrDefault(method.comment(), "处理 " + method.methodName() + " 协议事件。"));
            item.put("methodName", method.methodName());
            items.add(item);
        }
        model.put("methods", items);
        return model;
    }

    private Map<String, Object> dispatcherModel(
            final JavaLayout layout,
            final List<ProtocolMethod> methods,
            final JavaProjectModel project,
            final String dtoSuffix) {
        Set<String> imports = new TreeSet<>();
        imports.add("group.zn.zero.protocol.buffer.ZeroReader");
        addImport(imports, layout.dispatcherPackage(), layout.protocolPackage() + ".ProtocolIds");
        imports.add("java.util.HashMap");
        imports.add("java.util.Map");
        imports.add("java.util.Objects");
        Map<String, List<ProtocolMethod>> grouped = new LinkedHashMap<>();
        for (ProtocolMethod method : methods) {
            grouped.computeIfAbsent(method.boName(), ignored -> new ArrayList<>()).add(method);
            addImport(imports, layout.dispatcherPackage(),
                    layout.dtoPackage() + "." + dtoName(method.requestMessage(), dtoSuffix));
            addImport(imports, layout.dispatcherPackage(), layout.boPackage() + "." + method.boName());
            addImport(imports, layout.dispatcherPackage(),
                    layout.codecPackage() + "." + dtoName(method.requestMessage(), dtoSuffix) + "Codec");
        }

        List<Map<String, Object>> registrations = new ArrayList<>();
        for (Map.Entry<String, List<ProtocolMethod>> entry : grouped.entrySet()) {
            Map<String, Object> registration = new LinkedHashMap<>();
            registration.put("boName", entry.getKey());
            registration.put("fieldName", lowerFirst(entry.getKey()));
            registration.put("registerName", "register" + entry.getKey());
            List<Map<String, Object>> handlers = new ArrayList<>();
            for (ProtocolMethod method : entry.getValue()) {
                Map<String, Object> handler = new LinkedHashMap<>();
                handler.put("protocolConstant", constantName(method.definition().name()));
                handler.put("requestMessage", dtoName(method.requestMessage(), dtoSuffix));
                handler.put("codecName", dtoName(method.requestMessage(), dtoSuffix) + "Codec");
                handler.put("methodName", method.methodName());
                handler.put("arguments", dispatcherArguments(method, project.message(method.requestMessage())));
                handlers.add(handler);
            }
            registration.put("handlers", handlers);
            registrations.add(registration);
        }

        Map<String, Object> model = baseModel(layout.dispatcherPackage());
        model.put("imports", List.copyOf(imports));
        model.put("registrations", registrations);
        return model;
    }

    private Map<String, Object> codecModel(
            final JavaLayout layout,
            final ProtocolMessage message,
            final JavaProjectModel project,
            final String dtoSuffix) {
        Set<String> imports = new TreeSet<>();
        imports.add("group.zn.zero.protocol.buffer.ZeroReader");
        imports.add("group.zn.zero.protocol.buffer.ZeroWriter");
        imports.add("group.zn.zero.protocol.codec.ZeroPayloadCodec");
        imports.add("java.util.Objects");
        addImport(imports, layout.codecPackage(), layout.dtoPackage() + "." + dtoName(message.name(), dtoSuffix));
        for (ProtocolField field : message.fields()) {
            addTypeImports(layout.codecPackage(), layout.dtoPackage(), field.type(), imports, dtoSuffix);
        }

        List<ProtocolField> nullableFields = nullableFields(message.fields());
        List<Map<String, Object>> writeFields = new ArrayList<>();
        List<Map<String, Object>> readFields = new ArrayList<>();
        boolean unchecked = false;
        int nullableIndex = 0;
        for (ProtocolField field : message.fields()) {
            boolean fieldUnchecked = requiresUncheckedArrayCast(field.type());
            unchecked = unchecked || fieldUnchecked;
            Map<String, Object> writeField = new LinkedHashMap<>();
            writeField.put("name", field.name());
            writeField.put("nullable", field.nullable());
            writeField.put("presenceIndex", field.nullable() ? nullableIndex : -1);
            writeField.put("presentExpression", "message." + field.name() + " != null");
            String writeIndent = field.nullable() ? "            " : "        ";
            writeField.put("writeCode", writeValue(
                    field.type(),
                    "writer",
                    "message." + field.name(),
                    writeIndent,
                    imports,
                    layout.dtoPackage(),
                    project,
                    dtoSuffix));
            writeFields.add(writeField);

            Map<String, Object> readField = new LinkedHashMap<>();
            readField.put("name", field.name());
            readField.put("nullable", field.nullable());
            readField.put("presenceIndex", field.nullable() ? nullableIndex : -1);
            readField.put("readExpression", readValue(
                    field.type(),
                    "reader",
                    imports,
                    layout.dtoPackage(),
                    project,
                    dtoSuffix,
                    fieldUnchecked));
            readFields.add(readField);
            if (field.nullable()) {
                nullableIndex++;
            }
        }

        Map<String, Object> model = baseModel(layout.codecPackage());
        model.put("imports", List.copyOf(imports));
        model.put("messageName", dtoName(message.name(), dtoSuffix));
        model.put("codecName", dtoName(message.name(), dtoSuffix) + "Codec");
        model.put("codecProviderName", dtoName(message.name(), dtoSuffix) + "Codec");
        model.put("hasNullableFields", !nullableFields.isEmpty());
        model.put("nullableFieldCount", nullableFields.size());
        model.put("writeFields", writeFields);
        model.put("readFields", readFields);
        model.put("uncheckedRead", unchecked);
        return model;
    }

    private String dispatcherArguments(final ProtocolMethod method, final ProtocolMessage requestMessage) {
        if (!method.expandedParameters()) {
            return "request";
        }
        List<String> arguments = new ArrayList<>();
        for (ProtocolField field : requestMessage.fields()) {
            arguments.add("request." + field.name());
        }
        return String.join(", ", arguments);
    }

    private String methodSignature(final ProtocolMethod method, final String dtoSuffix) {
        if (method.expandedParameters()) {
            List<String> parameters = new ArrayList<>();
            Set<String> imports = new TreeSet<>();
            for (ProtocolField parameter : method.parameters()) {
                parameters.add(typeMapper.fieldType(parameter, imports, dtoSuffix) + " " + parameter.name());
            }
            return "void " + method.methodName() + "(" + String.join(", ", parameters) + ")";
        }
        String returnType = method.responseMessage().isBlank() ? "void" : dtoName(method.responseMessage(), dtoSuffix);
        return returnType + " " + method.methodName() + "(" + dtoName(method.requestMessage(), dtoSuffix)
                + " request)";
    }

    private Set<String> methodImports(
            final String packageName,
            final String dtoPackage,
            final List<ProtocolMethod> methods,
            final String dtoSuffix) {
        Set<String> imports = new TreeSet<>();
        for (ProtocolMethod method : methods) {
            if (!method.expandedParameters()) {
                addImport(imports, packageName, dtoPackage + "." + dtoName(method.requestMessage(), dtoSuffix));
            } else {
                for (ProtocolField parameter : method.parameters()) {
                    typeMapper.fieldType(parameter, imports, dtoSuffix);
                    addTypeImports(packageName, dtoPackage, parameter.type(), imports, dtoSuffix);
                }
            }
            if (!method.responseMessage().isBlank()) {
                addImport(imports, packageName, dtoPackage + "." + dtoName(method.responseMessage(), dtoSuffix));
            }
        }
        return imports;
    }

    private List<ProtocolField> nullableFields(final List<ProtocolField> fields) {
        List<ProtocolField> result = new ArrayList<>();
        for (ProtocolField field : fields) {
            if (field.nullable()) {
                result.add(field);
            }
        }
        return result;
    }

    private void addTypeImports(
            final String packageName,
            final String dtoPackage,
            final ProtocolType type,
            final Set<String> imports,
            final String dtoSuffix) {
        switch (type.kind()) {
            case ENUM -> addImport(imports, packageName, dtoPackage + "." + type.name());
            case MESSAGE -> addImport(imports, packageName, dtoPackage + "." + dtoName(type.name(), dtoSuffix));
            case LIST -> imports.add("java.util.List");
            case SET -> imports.add("java.util.Set");
            case MAP -> imports.add("java.util.Map");
            default -> {
                // 标量和数组本身不需要 import。
            }
        }
        for (ProtocolType argument : type.arguments()) {
            addTypeImports(packageName, dtoPackage, argument, imports, dtoSuffix);
        }
    }

    private String writeValue(
            final ProtocolType type,
            final String writer,
            final String value,
            final String indent,
            final Set<String> imports,
            final String namespace,
            final JavaProjectModel project,
            final String dtoSuffix) {
        StringBuilder builder = new StringBuilder();
        switch (type.kind()) {
            case SCALAR -> appendLine(builder, indent, scalarWrite(writer, value, type.name()));
            case ENUM -> appendLine(builder, indent, writer + ".writeInt(Objects.requireNonNull("
                    + value + ", \"" + value + "\").value());");
            case MESSAGE -> appendLine(builder, indent, dtoName(type.name(), dtoSuffix) + "Codec.INSTANCE.write("
                    + writer + ", " + value + ");");
            case LIST, SET -> {
                String itemWriter = childName(writer, "ItemWriter");
                String itemValue = childName(value, "ItemValue");
                appendLine(builder, indent, writer + ".writeCollection(" + value + ", (" + itemWriter + ", "
                        + itemValue + ") -> {");
                builder.append(writeValue(type.arguments().get(0), itemWriter, itemValue,
                        indent + "    ", imports, namespace, project, dtoSuffix));
                appendLine(builder, indent, "});");
            }
            case MAP -> {
                String keyWriter = childName(writer, "KeyWriter");
                String keyValue = childName(value, "KeyValue");
                String valueWriter = childName(writer, "ValueWriter");
                String mapValue = childName(value, "MapValue");
                appendLine(builder, indent, writer + ".writeMap(" + value + ", (" + keyWriter + ", "
                        + keyValue + ") -> {");
                builder.append(writeValue(type.arguments().get(0), keyWriter, keyValue,
                        indent + "    ", imports, namespace, project, dtoSuffix));
                appendLine(builder, indent, "}, (" + valueWriter + ", " + mapValue + ") -> {");
                builder.append(writeValue(type.arguments().get(1), valueWriter, mapValue,
                        indent + "    ", imports, namespace, project, dtoSuffix));
                appendLine(builder, indent, "});");
            }
            case ARRAY -> builder.append(writeArray(type, writer, value, indent, imports, namespace, project,
                    dtoSuffix));
            case OPTIONAL -> {
                appendLine(builder, indent, writer + ".writeBoolean(" + value + " != null);");
                appendLine(builder, indent, "if (" + value + " != null) {");
                builder.append(writeValue(type.arguments().get(0), writer, value,
                        indent + "    ", imports, namespace, project, dtoSuffix));
                appendLine(builder, indent, "}");
            }
            case NULL -> appendLine(builder, indent, "throw new IllegalArgumentException(\"null type is reserved\");");
            default -> throw new IllegalStateException("unsupported type kind: " + type.kind());
        }
        return builder.toString();
    }

    private String writeArray(
            final ProtocolType type,
            final String writer,
            final String value,
            final String indent,
            final Set<String> imports,
            final String namespace,
            final JavaProjectModel project,
            final String dtoSuffix) {
        ProtocolType elementType = type.arguments().get(0);
        String scalarName = scalarArrayName(elementType);
        if (!scalarName.isBlank()) {
            return indent + writer + ".write" + scalarName + "Array(" + value + ");" + System.lineSeparator();
        }
        String itemWriter = childName(writer, "ArrayWriter");
        String itemValue = childName(value, "ArrayValue");
        StringBuilder builder = new StringBuilder();
        appendLine(builder, indent, writer + ".writeArray(" + value + ", (" + itemWriter + ", " + itemValue
                + ") -> {");
        builder.append(writeValue(elementType, itemWriter, itemValue, indent + "    ", imports, namespace, project,
                dtoSuffix));
        appendLine(builder, indent, "});");
        return builder.toString();
    }

    private String readValue(
            final ProtocolType type,
            final String reader,
            final Set<String> imports,
            final String namespace,
            final JavaProjectModel project,
            final String dtoSuffix,
            final boolean uncheckedContext) {
        return switch (type.kind()) {
            case SCALAR -> scalarRead(reader, type.name());
            case ENUM -> type.name() + ".fromValue(" + reader + ".readInt())";
            case MESSAGE -> dtoName(type.name(), dtoSuffix) + "Codec.INSTANCE.read(" + reader + ")";
            case LIST -> reader + ".readList(" + childName(reader, "ItemReader") + " -> "
                    + readValue(type.arguments().get(0), childName(reader, "ItemReader"), imports, namespace,
                    project, dtoSuffix, uncheckedContext) + ")";
            case SET -> reader + ".readSet(" + childName(reader, "ItemReader") + " -> "
                    + readValue(type.arguments().get(0), childName(reader, "ItemReader"), imports, namespace,
                    project, dtoSuffix, uncheckedContext) + ")";
            case MAP -> reader + ".readMap(" + childName(reader, "KeyReader") + " -> "
                    + readValue(type.arguments().get(0), childName(reader, "KeyReader"), imports, namespace,
                    project, dtoSuffix, uncheckedContext) + ", " + childName(reader, "ValueReader") + " -> "
                    + readValue(type.arguments().get(1), childName(reader, "ValueReader"), imports, namespace,
                    project, dtoSuffix, uncheckedContext) + ")";
            case ARRAY -> readArray(type, reader, imports, namespace, project, dtoSuffix, uncheckedContext);
            case OPTIONAL -> "(" + reader + ".readBoolean() ? "
                    + readValue(type.arguments().get(0), reader, imports, namespace, project, dtoSuffix,
                    uncheckedContext)
                    + " : null)";
            case NULL -> "null";
        };
    }

    private String readArray(
            final ProtocolType type,
            final String reader,
            final Set<String> imports,
            final String namespace,
            final JavaProjectModel project,
            final String dtoSuffix,
            final boolean uncheckedContext) {
        ProtocolType elementType = type.arguments().get(0);
        String scalarName = scalarArrayName(elementType);
        if (!scalarName.isBlank()) {
            return reader + ".read" + scalarName + "Array()";
        }
        String itemReader = childName(reader, "ArrayReader");
        String expression = reader + ".readArray(" + classLiteral(elementType, imports, dtoSuffix) + ", "
                + itemReader + " -> "
                + readValue(elementType, itemReader, imports, namespace, project, dtoSuffix, uncheckedContext) + ")";
        if (requiresUncheckedArrayCast(type)) {
            expression = "(" + javaType(type, imports, dtoSuffix) + ") " + expression;
        }
        return expression;
    }

    private String classLiteral(final ProtocolType type, final Set<String> imports, final String dtoSuffix) {
        return switch (type.kind()) {
            case SCALAR -> boxedScalarClass(type.name()) + ".class";
            case ENUM -> type.name() + ".class";
            case MESSAGE -> dtoName(type.name(), dtoSuffix) + ".class";
            case LIST -> {
                imports.add("java.util.List");
                yield "List.class";
            }
            case SET -> {
                imports.add("java.util.Set");
                yield "Set.class";
            }
            case MAP -> {
                imports.add("java.util.Map");
                yield "Map.class";
            }
            case ARRAY -> javaType(type, imports, dtoSuffix) + ".class";
            case OPTIONAL -> classLiteral(type.arguments().get(0), imports, dtoSuffix);
            case NULL -> "Object.class";
        };
    }

    private String javaType(final ProtocolType type, final Set<String> imports, final String dtoSuffix) {
        ProtocolField synthetic = new ProtocolField("value", type, 1, false, false, "");
        return typeMapper.fieldType(synthetic, imports, dtoSuffix);
    }

    private String scalarWrite(final String writer, final String value, final String scalarName) {
        return switch (scalarName) {
            case "boolean" -> writer + ".writeBoolean(" + value + ");";
            case "byte" -> writer + ".writeByte(" + value + ");";
            case "short" -> writer + ".writeShort(" + value + ");";
            case "int" -> writer + ".writeInt(" + value + ");";
            case "uint", "id", "count" -> writer + ".writeUnsignedInt(" + value + ");";
            case "long" -> writer + ".writeLong(" + value + ");";
            case "ulong" -> writer + ".writeUnsignedLong(" + value + ");";
            case "float" -> writer + ".writeFloat(" + value + ");";
            case "double" -> writer + ".writeDouble(" + value + ");";
            case "string" -> writer + ".writeString(" + value + ");";
            case "bytes" -> writer + ".writeByteArray(" + value + ");";
            default -> throw new IllegalStateException("unsupported scalar type: " + scalarName);
        };
    }

    private String scalarRead(final String reader, final String scalarName) {
        return switch (scalarName) {
            case "boolean" -> reader + ".readBoolean()";
            case "byte" -> reader + ".readByte()";
            case "short" -> reader + ".readShort()";
            case "int" -> reader + ".readInt()";
            case "uint", "id", "count" -> reader + ".readUnsignedInt()";
            case "long" -> reader + ".readLong()";
            case "ulong" -> reader + ".readUnsignedLong()";
            case "float" -> reader + ".readFloat()";
            case "double" -> reader + ".readDouble()";
            case "string" -> reader + ".readString()";
            case "bytes" -> reader + ".readByteArray()";
            default -> throw new IllegalStateException("unsupported scalar type: " + scalarName);
        };
    }

    private String scalarArrayName(final ProtocolType type) {
        if (type.kind() != ProtocolTypeKind.SCALAR) {
            return "";
        }
        return switch (type.name()) {
            case "boolean" -> "Boolean";
            case "byte" -> "Byte";
            case "short" -> "Short";
            case "int" -> "Int";
            case "long" -> "Long";
            case "float" -> "Float";
            case "double" -> "Double";
            default -> "";
        };
    }

    private String boxedScalarClass(final String scalarName) {
        return switch (scalarName) {
            case "boolean" -> "Boolean";
            case "byte" -> "Byte";
            case "short" -> "Short";
            case "int", "uint", "id", "count" -> "Integer";
            case "long", "ulong" -> "Long";
            case "float" -> "Float";
            case "double" -> "Double";
            case "string" -> "String";
            case "bytes" -> "byte[]";
            default -> "Object";
        };
    }

    private boolean requiresUncheckedArrayCast(final ProtocolType type) {
        if (type.kind() != ProtocolTypeKind.ARRAY) {
            for (ProtocolType argument : type.arguments()) {
                if (requiresUncheckedArrayCast(argument)) {
                    return true;
                }
            }
            return false;
        }
        ProtocolType element = type.arguments().get(0);
        return element.kind() == ProtocolTypeKind.LIST
                || element.kind() == ProtocolTypeKind.SET
                || element.kind() == ProtocolTypeKind.MAP
                || requiresUncheckedArrayCast(element);
    }

    private String renderTemplate(final String templateName, final Map<String, Object> model) {
        try {
            Template template = configuration.getTemplate(templateName);
            StringWriter writer = new StringWriter(4096);
            template.process(model, writer);
            return writer.toString();
        } catch (IOException | TemplateException ex) {
            throw ZeroException.of(
                    CodegenErrorCode.OUTPUT_FAILED,
                    "failed to render template: " + templateName,
                    ex);
        }
    }

    private Map<String, Object> baseModel(final String packageName) {
        Map<String, Object> model = new LinkedHashMap<>();
        model.put("generatedMarker", GENERATED_MARKER);
        model.put("packageName", packageName);
        model.put("imports", List.of());
        return model;
    }

    private static void addImport(final Set<String> imports, final String packageName, final String fullyQualifiedName) {
        int packageEnd = fullyQualifiedName.lastIndexOf('.');
        if (packageEnd <= 0) {
            return;
        }
        String importPackage = fullyQualifiedName.substring(0, packageEnd);
        if (!packageName.equals(importPackage)) {
            imports.add(fullyQualifiedName);
        }
    }

    private static Path packageDir(final Path outputDir, final String packageName) {
        return outputDir.resolve(packageName.replace('.', '/'));
    }

    private String codecLiteral(final ProtocolDefinition protocol) {
        if (ProtocolDefinition.DEFAULT_CODEC.equals(protocol.codecName())) {
            return "ProtocolDefinition.DEFAULT_CODEC";
        }
        return "\"" + protocol.codecName() + "\"";
    }

    private String featureSet(final Set<ProtocolFeature> features) {
        if (features.isEmpty()) {
            return "Set.of()";
        }
        List<String> names = new ArrayList<>();
        for (ProtocolFeature feature : features) {
            names.add("ProtocolFeature." + feature.name());
        }
        return "Set.of(" + String.join(", ", names) + ")";
    }

    private String implementationName(final String boName) {
        if (boName.startsWith("I")
                && boName.endsWith("BO")
                && boName.length() > 3
                && Character.isUpperCase(boName.charAt(1))) {
            return boName.substring(1) + "Imp";
        }
        return boName + "Imp";
    }

    private String dtoName(final String logicalName, final String dtoSuffix) {
        return logicalName + dtoSuffix;
    }

    private String constantName(final String value) {
        StringBuilder builder = new StringBuilder(value.length() + 8);
        char previous = 0;
        for (int index = 0; index < value.length(); index++) {
            char current = value.charAt(index);
            if (Character.isUpperCase(current) && index > 0 && Character.isLowerCase(previous)) {
                builder.append('_');
            }
            if (Character.isLetterOrDigit(current)) {
                builder.append(Character.toUpperCase(current));
            } else if (builder.length() > 0 && builder.charAt(builder.length() - 1) != '_') {
                builder.append('_');
            }
            previous = current;
        }
        return builder.toString();
    }

    private String lowerFirst(final String value) {
        if (value.isEmpty()) {
            return value;
        }
        return Character.toLowerCase(value.charAt(0)) + value.substring(1);
    }

    private String childName(final String owner, final String suffix) {
        StringBuilder builder = new StringBuilder(owner.length() + suffix.length());
        for (int index = 0; index < owner.length(); index++) {
            char value = owner.charAt(index);
            if (Character.isLetterOrDigit(value)) {
                builder.append(value);
            }
        }
        if (builder.length() == 0) {
            builder.append("value");
        }
        builder.append(suffix);
        return builder.toString();
    }

    private String commentOrDefault(final String comment, final String defaultValue) {
        if (comment == null || comment.isBlank()) {
            return defaultValue;
        }
        return comment;
    }

    private void appendLine(final StringBuilder builder, final String indent, final String line) {
        builder.append(indent).append(line).append(System.lineSeparator());
    }

    private void writeGeneratedFile(final Path path, final String content) {
        try {
            Path parent = path.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            if (Files.exists(path)) {
                String existing = Files.readString(path, StandardCharsets.UTF_8);
                if (!existing.contains(GENERATED_MARKER)) {
                    throw ZeroException.of(
                            CodegenErrorCode.OUTPUT_FAILED,
                            "refuse to overwrite non-generated file: " + path,
                            null);
                }
            }
            Files.writeString(path, content, StandardCharsets.UTF_8);
        } catch (IOException ex) {
            throw ZeroException.of(CodegenErrorCode.OUTPUT_FAILED, "failed to write generated file: " + path, ex);
        }
    }

    /**
     * Java 生成物布局。
     *
     * @param dtoDir DTO 输出目录。
     * @param dtoPackage DTO 包名。
     * @param codecDir codec 输出目录。
     * @param codecPackage codec 包名。
     * @param protocolDir 协议定义输出目录。
     * @param protocolPackage 协议定义包名。
     * @param boDir BO 输出目录。
     * @param boPackage BO 包名。
     * @param boImplDir BOImp 输出目录。
     * @param boImplPackage BOImp 包名。
     * @param dispatcherDir dispatcher 输出目录。
     * @param dispatcherPackage dispatcher 包名。
     */
    private record JavaLayout(
            Path dtoDir,
            String dtoPackage,
            Path codecDir,
            String codecPackage,
            Path protocolDir,
            String protocolPackage,
            Path boDir,
            String boPackage,
            Path boImplDir,
            String boImplPackage,
            Path dispatcherDir,
            String dispatcherPackage) {

        /**
         * 基于生成请求创建布局。
         *
         * @param request 代码生成请求；不允许为空。
         * @return Java 生成物布局；不允许为空。
         */
        static JavaLayout from(final CodegenRequest request) {
            Objects.requireNonNull(request, "request");
            String dtoPackage = request.javaPackage(JavaArtifactKind.DTO);
            String codecPackage = request.javaPackage(JavaArtifactKind.CODEC);
            String protocolPackage = request.javaPackage(JavaArtifactKind.PROTOCOL);
            String boPackage = request.javaPackage(JavaArtifactKind.BO);
            String boImplPackage = request.javaPackage(JavaArtifactKind.BO_IMPL);
            String dispatcherPackage = request.javaPackage(JavaArtifactKind.DISPATCHER);
            return new JavaLayout(
                    packageDir(request.javaOutputDir(JavaArtifactKind.DTO), dtoPackage),
                    dtoPackage,
                    packageDir(request.javaOutputDir(JavaArtifactKind.CODEC), codecPackage),
                    codecPackage,
                    packageDir(request.javaOutputDir(JavaArtifactKind.PROTOCOL), protocolPackage),
                    protocolPackage,
                    packageDir(request.javaOutputDir(JavaArtifactKind.BO), boPackage),
                    boPackage,
                    packageDir(request.javaOutputDir(JavaArtifactKind.BO_IMPL), boImplPackage),
                    boImplPackage,
                    packageDir(request.javaOutputDir(JavaArtifactKind.DISPATCHER), dispatcherPackage),
                    dispatcherPackage);
        }

        /**
         * 创建 Java 生成物布局。
         *
         * @throws NullPointerException 当任意目录或包名为空时抛出。
         */
        JavaLayout {
            Objects.requireNonNull(dtoDir, "dtoDir");
            Objects.requireNonNull(dtoPackage, "dtoPackage");
            Objects.requireNonNull(codecDir, "codecDir");
            Objects.requireNonNull(codecPackage, "codecPackage");
            Objects.requireNonNull(protocolDir, "protocolDir");
            Objects.requireNonNull(protocolPackage, "protocolPackage");
            Objects.requireNonNull(boDir, "boDir");
            Objects.requireNonNull(boPackage, "boPackage");
            Objects.requireNonNull(boImplDir, "boImplDir");
            Objects.requireNonNull(boImplPackage, "boImplPackage");
            Objects.requireNonNull(dispatcherDir, "dispatcherDir");
            Objects.requireNonNull(dispatcherPackage, "dispatcherPackage");
        }
    }

    /**
     * Java 协议工程辅助模型。
     *
     * @param messages 协议消息映射。
     */
    private record JavaProjectModel(Map<String, ProtocolMessage> messages) {

        /**
         * 创建 Java 协议工程辅助模型。
         *
         * @param sourceMessages 协议消息列表；不可为空。
         */
        JavaProjectModel(final List<ProtocolMessage> sourceMessages) {
            this(toMessageMap(sourceMessages));
        }

        /**
         * 创建 Java 协议工程辅助模型。
         *
         * @throws NullPointerException 当 Java 包名或消息映射为空时抛出。
         */
        JavaProjectModel {
            Objects.requireNonNull(messages, "messages");
        }

        /**
         * 返回指定协议消息。
         *
         * @param name 消息名称；不可为空。
         * @return 协议消息；不可为空；线程安全。
         */
        ProtocolMessage message(final String name) {
            ProtocolMessage message = messages.get(name);
            if (message == null) {
                throw ZeroException.of(
                        CodegenErrorCode.DSL_VALIDATION_FAILED,
                        "unknown message: " + name,
                        null);
            }
            return message;
        }

        private static Map<String, ProtocolMessage> toMessageMap(final List<ProtocolMessage> sourceMessages) {
            Map<String, ProtocolMessage> result = new LinkedHashMap<>();
            for (ProtocolMessage message : sourceMessages) {
                result.put(message.name(), message);
            }
            return Map.copyOf(result);
        }
    }
}
